### ISSUE TITLE
Update PDF

### ISSUE THREAD

**Issue by KOLANICH** [Maijin/radare2book#25]
Also write in Readme.md how to generate pdf from this repo.

**Comment by Maijin** [comment]
better than a reame, a damn script :+1:

**Comment by Maijin** [comment]
Now it's done automaticly thanks to gitbook interface  https://www.gitbook.com/download/pdf/book/maijin/radare2book

**Comment by KOLANICH** [comment]
Thank you.

**Comment by Maijin** [comment]
@KOLANICH expect some more updates
